[package]
name = "gpt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "0.27.2"
clap = { version = "4.5.30", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }
tokio-stream = "0.1.17"
